//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Id { get; set; }
        public string CurrencyName { get; set; }
        public double CurrencyValue { get; set; }
        public System.DateTime CurrencyLastUpdate { get; set; }
        public string CurrencyService { get; set; }
    }
}
